name: CICD Workflow

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        run: echo "Cloning the repository..."
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build using docker
        run: echo "Building the application..."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing the application
        run: echo "Testing the application..."

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the application
        run: echo "Deploying the application..."
